### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by vjpr** [lint-deps/lint-deps#13]
```
> deps

/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/lint-deps/node_modules/strip-comments/node_modules/extract-comments/lib/comments.js:55
      throw err;
      ^
Error: Line 3: Unexpected token <
    at constructError (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/lint-deps/node_modules/strip-comments/node_modules/extract-comments/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2406:21)
    at createError (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/lint-deps/node_modules/strip-comments/node_modules/extract-comments/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/lint-deps/node_modules/strip-comments/node_modules/extract-comments/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2499:13)
    at throwUnexpectedToken (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/lint-deps/node_modules/strip-comments/node_modules/extract-comments/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2504:15)
    at parsePrimaryExpression (/Users/Vaughan/nvm/versions/node/v6.0%
```

**Comment by doowb** [comment]
There's probably a syntax error inside your javascript. Use `eslint` to find and fix the error, then try running `lint-deps`.

**Comment by jonschlinkert** [comment]
I just noticed this error myself. I'm thinking about switching back to a non-esprima lib to strip comments.

**Comment by jonschlinkert** [comment]
closing based on age
